# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Waurisch\WrsPannellum\:
    resource: '../Classes/*'

  flexformservice:
    class: 'TYPO3\CMS\Core\Service\FlexFormService'

  Waurisch\WrsPannellum\DataProcessor\FlexFormProcessor:
    public: true
    arguments:
      $flexFormService: '@flexformservice'